import html2canvas from 'html2canvas'
import jsPDF from 'jspdf'

type ScorecardTotals = {
  met: number
  failed: number
  consideration: number
  na: number
}

type ScorecardRow = {
  label: string
  overall: string
  failedIndicators: string
  considerationIndicators: string
}

type ScorecardData = {
  title: string
  subtitle?: string
  totals: ScorecardTotals
  metaRows: Array<[string, string]>
  rows: ScorecardRow[]
}

type GovernanceAuditRow = {
  audit: string
  latestYear: string
  value: string
  label: string
  coverage: string
}

type GovernanceScorecardData = {
  title: string
  subtitle?: string
  metaRows: Array<[string, string]>
  auditRows: GovernanceAuditRow[]
  sglgTotals: ScorecardTotals
  sglgRows: ScorecardRow[]
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

export function buildSglgScorecardHtml(data: ScorecardData) {
  const metaRows = data.metaRows.map(([label, value]) => (
    `<tr><th>${escapeHtml(label)}</th><td>${escapeHtml(value || '-')}</td></tr>`
  )).join('')

  const rowsHtml = data.rows.map((row) => (
    `<tr>
      <td>${escapeHtml(row.label)}</td>
      <td>${escapeHtml(row.overall)}</td>
      <td>${escapeHtml(row.failedIndicators || '-')}</td>
      <td>${escapeHtml(row.considerationIndicators || '-')}</td>
    </tr>`
  )).join('')

  return `
    <style>
      * { box-sizing: border-box; }
      body { font-family: Arial, sans-serif; color: #111827; padding: 24px 24px 96px; }
      h1 { font-size: 20px; margin: 0 0 8px; }
      h2 { font-size: 14px; margin: 16px 0 8px; }
      table { width: 100%; border-collapse: collapse; font-size: 12px; }
      th, td { border: 1px solid #e5e7eb; padding: 6px 8px; text-align: left; vertical-align: top; }
      th { background: #f3f4f6; }
      .summary { display: flex; gap: 12px; margin: 12px 0; font-size: 12px; flex-wrap: wrap; }
      .pill { border: 1px solid #e5e7eb; border-radius: 999px; padding: 4px 10px; background: #f9fafb; }
      .subtitle { font-size: 12px; color: #6b7280; margin-bottom: 12px; }
      .footer { margin-top: 16px; font-size: 11px; color: #6b7280; padding-bottom: 24px; }
    </style>
    <div>
      <h1>${escapeHtml(data.title)}</h1>
      ${data.subtitle ? `<div class="subtitle">${escapeHtml(data.subtitle)}</div>` : ''}
      <div class="summary">
        <div class="pill">Met: ${data.totals.met}</div>
        <div class="pill">Failed: ${data.totals.failed}</div>
        <div class="pill">Consideration: ${data.totals.consideration}</div>
        <div class="pill">N/A: ${data.totals.na}</div>
      </div>
      <h2>LGU Profile</h2>
      <table>
        <tbody>
          ${metaRows}
        </tbody>
      </table>
      <h2>Criteria Summary</h2>
      <table>
        <thead>
          <tr>
            <th>Criteria</th>
            <th>Overall</th>
            <th>Failed Indicators</th>
            <th>Consideration Indicators</th>
          </tr>
        </thead>
        <tbody>
          ${rowsHtml}
        </tbody>
      </table>
      <div class="footer">
        Generated by DataForge. Use this scorecard for planning and intervention tracking.
      </div>
    </div>
  `
}

export function buildGovernanceScorecardHtml(data: GovernanceScorecardData) {
  const metaRows = data.metaRows.map(([label, value]) => (
    `<tr><th>${escapeHtml(label)}</th><td>${escapeHtml(value || '-')}</td></tr>`
  )).join('')

  const auditRows = data.auditRows.length
    ? data.auditRows.map((row) => (
    `<tr>
      <td>${escapeHtml(row.audit)}</td>
      <td>${escapeHtml(row.latestYear)}</td>
      <td>${escapeHtml(row.value)}</td>
      <td>${escapeHtml(row.label)}</td>
      <td>${escapeHtml(row.coverage)}</td>
    </tr>`
  )).join('')
    : `<tr><td colspan="5">No audit data</td></tr>`

  const sglgRows = data.sglgRows.map((row) => (
    `<tr>
      <td>${escapeHtml(row.label)}</td>
      <td>${escapeHtml(row.overall)}</td>
      <td>${escapeHtml(row.failedIndicators || '-')}</td>
      <td>${escapeHtml(row.considerationIndicators || '-')}</td>
    </tr>`
  )).join('')

  return `
    <style>
      * { box-sizing: border-box; }
      body { font-family: Arial, sans-serif; color: #111827; padding: 24px 24px 96px; }
      h1 { font-size: 20px; margin: 0 0 8px; }
      h2 { font-size: 14px; margin: 16px 0 8px; }
      table { width: 100%; border-collapse: collapse; font-size: 12px; }
      th, td { border: 1px solid #e5e7eb; padding: 6px 8px; text-align: left; vertical-align: top; }
      th { background: #f3f4f6; }
      .summary { display: flex; gap: 12px; margin: 12px 0; font-size: 12px; flex-wrap: wrap; }
      .pill { border: 1px solid #e5e7eb; border-radius: 999px; padding: 4px 10px; background: #f9fafb; }
      .subtitle { font-size: 12px; color: #6b7280; margin-bottom: 12px; }
      .footer { margin-top: 16px; font-size: 11px; color: #6b7280; padding-bottom: 24px; }
    </style>
    <div>
      <h1>${escapeHtml(data.title)}</h1>
      ${data.subtitle ? `<div class="subtitle">${escapeHtml(data.subtitle)}</div>` : ''}
      <h2>LGU Profile</h2>
      <table>
        <tbody>
          ${metaRows}
        </tbody>
      </table>

      <h2>Audit Summary (Latest Available)</h2>
      <table>
        <thead>
          <tr>
            <th>Audit</th>
            <th>Latest Year</th>
            <th>Status / Value</th>
            <th>Label</th>
            <th>Coverage</th>
          </tr>
        </thead>
        <tbody>
          ${auditRows || `<tr><td colspan="5">No audit data</td></tr>`}
        </tbody>
      </table>

      <h2>SGLG Summary (2024)</h2>
      <div class="summary">
        <div class="pill">Met: ${data.sglgTotals.met}</div>
        <div class="pill">Failed: ${data.sglgTotals.failed}</div>
        <div class="pill">Consideration: ${data.sglgTotals.consideration}</div>
        <div class="pill">N/A: ${data.sglgTotals.na}</div>
      </div>
      <table>
        <thead>
          <tr>
            <th>Criteria</th>
            <th>Overall</th>
            <th>Failed Indicators</th>
            <th>Consideration Indicators</th>
          </tr>
        </thead>
        <tbody>
          ${sglgRows}
        </tbody>
      </table>
      <div class="footer">
        Generated by DataForge. Use this scorecard for planning and intervention tracking.
      </div>
    </div>
  `
}

export async function openScorecardPdf(html: string, filename: string) {
  const pendingWindow = window.open('', '_blank')
  const container = document.createElement('div')
  container.innerHTML = html
  container.style.position = 'fixed'
  container.style.left = '-10000px'
  container.style.top = '0'
  container.style.width = '800px'
  container.style.background = 'white'
  document.body.appendChild(container)

  const canvas = await html2canvas(container, {
    scale: 2,
    backgroundColor: '#ffffff',
    useCORS: true,
    windowWidth: 800,
  })
  const imgData = canvas.toDataURL('image/png')
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 36
  const contentWidth = pageWidth - margin * 2
  const scale = contentWidth / canvas.width
  const pageHeightPx = (pageHeight - margin * 2) / scale - 20

  let yOffset = 0
  let pageIndex = 0
  while (yOffset < canvas.height) {
    const sliceHeight = Math.min(pageHeightPx, canvas.height - yOffset)
    const sliceCanvas = document.createElement('canvas')
    sliceCanvas.width = canvas.width
    sliceCanvas.height = sliceHeight
    const ctx = sliceCanvas.getContext('2d')
    if (!ctx) break
    ctx.drawImage(
      canvas,
      0,
      yOffset,
      canvas.width,
      sliceHeight,
      0,
      0,
      canvas.width,
      sliceHeight,
    )
    const sliceData = sliceCanvas.toDataURL('image/png')
    const sliceHeightPt = sliceHeight * scale
    if (pageIndex > 0) doc.addPage()
    doc.addImage(sliceData, 'PNG', margin, margin, contentWidth, sliceHeightPt)
    yOffset += sliceHeight
    pageIndex += 1
  }

  const blob = doc.output('blob')
  const url = URL.createObjectURL(blob)
  let opened = false
  if (pendingWindow) {
    pendingWindow.location.href = url
    opened = true
  } else {
    const win = window.open(url, '_blank')
    opened = !!win
  }
  if (!opened) {
    doc.save(filename)
  }
  setTimeout(() => URL.revokeObjectURL(url), 60_000)

  document.body.removeChild(container)
}
